name: Cypress Tests

on:
  workflow_dispatch:    # Ejecución manual

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run All Tests
        id: cypress-tests
        continue-on-error: true
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: 'cypress/e2e/logindistribucion/*.cy.js'
          config-file: cypress.config.js

      - name: Report Test Results
        if: always()
        run: |
          echo "🧪 Test Results Summary:"
          echo "======================="
          echo "Tests Executed:"
          
          # Verificar el estado de cada test individualmente
          if [ -f "cypress/results.json" ]; then
            # Login Invalid Password Test
            if grep -q "Login Invalid Password Test.*failed" cypress/results.json; then
              echo "- Login Invalid Password Test ❌ FAILED"
            else
              echo "- Login Invalid Password Test ✅ PASSED"
            fi
            
            # Login Invalid User Test
            if grep -q "Login Invalid User Test.*failed" cypress/results.json; then
              echo "- Login Invalid User Test ❌ FAILED"
            else
              echo "- Login Invalid User Test ✅ PASSED"
            fi
            
            # Login Success Test
            if grep -q "Login Success Test.*failed" cypress/results.json; then
              echo "- Login Success Test ❌ FAILED"
            else
              echo "- Login Success Test ✅ PASSED"
            fi
          else
            echo "- Login Invalid Password Test ❌ FAILED (No results file)"
            echo "- Login Invalid User Test ❌ FAILED (No results file)"
            echo "- Login Success Test ❌ FAILED (No results file)"
          fi
          
          echo ""
          echo "Results Details:"
          if [ -f "cypress/results.json" ]; then
            cat cypress/results.json | jq -r '
              if . then
                "Total Tests: " + (.stats.tests | tostring) + "\n" +
                "Passed: " + (.stats.passes | tostring) + "\n" +
                "Failed: " + (.stats.failures | tostring) + "\n" +
                "Skipped: " + (.stats.pending | tostring)
              else
                "No valid results found"
              end
            ' || echo "Error parsing results"
          else
            echo "No results file found"
            echo "Total Tests: 3"
            echo "Failed: 3"
            echo "Passed: 0"
            echo "Skipped: 0"
          fi
          echo "======================="

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Set final status
        if: always()
        run: |
          if [[ "${{ steps.cypress-tests.outcome }}" == "failure" ]]; then
            echo "❌ Some tests failed or were skipped"
            echo "Check the detailed report above for more information"
            exit 1
          else
            echo "✅ All tests completed successfully"
            exit 0
          fi 