name: Cypress Tests

on:
  workflow_dispatch:    # Ejecución manual

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run All Tests
        id: cypress-tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: 'cypress/e2e/logindistribucion/*.cy.js'
          config-file: cypress.config.js
          record: false
          parallel: false

      - name: Report Test Results
        if: always()
        run: |
          echo "🧪 Test Results Summary:"
          echo "======================="
          echo "Tests Executed:"
          for file in cypress/e2e/logindistribucion/*.cy.js; do
            testname=$(basename "$file" .cy.js)
            if [ -f "cypress/results/$testname.json" ]; then
              result=$(cat "cypress/results/$testname.json")
              if echo "$result" | grep -q '"state": "failed"'; then
                echo "❌ $testname: FAILED"
              else
                echo "✅ $testname: PASSED"
              fi
            else
              echo "⚠️ $testname: NO RESULTS"
            fi
          done
          
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Set final status
        if: always()
        run: |
          if [ -d "cypress/results" ] && [ "$(find cypress/results -name '*.json' | wc -l)" -gt 0 ]; then
            if grep -r '"state": "failed"' cypress/results; then
              echo "❌ Some tests failed"
              exit 1
            else
              echo "✅ All tests passed"
              exit 0
            fi
          else
            echo "❌ No test results found"
            exit 1
          fi 