name: Cypress Tests

on:
  workflow_dispatch:    # Ejecución manual

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run All Tests
        id: cypress-tests
        continue-on-error: true
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: 'cypress/e2e/logindistribucion/*.cy.js'
          config-file: cypress.config.js

      - name: Report Test Results
        if: always()
        run: |
          echo "Test Results Summary:"
          echo "===================="
          RESULTS=$(cat cypress/results.json 2>/dev/null || echo '{}')
          echo "$RESULTS" | jq -r '.results[] | "Test: \(.title) - Status: \(if .state == "passed" then "OK" else "failure" end)"' || echo "No results found"
          echo "===================="
          
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Set final status
        if: always()
        run: |
          if [[ "${{ steps.cypress-tests.outcome }}" == "failure" ]]; then
            echo "Some tests failed"
            exit 1
          else
            echo "All tests passed"
            exit 0
          fi 